- name: Create CentOS 7 Base Image
  hosts: all
  pre_tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
  roles:
    - name: dev-sec.os-hardening
    - name: dev-sec.ssh-hardening
  vars:
    ssh_allow_root_with_key: yes
    ssh_max_auth_retries: 3
    ssh_use_pam: yes
    ssh_deny_users: "toor administrator administrateur admin adm test guest info mysql user oracle"
    sftp_enabled: true
    swap_size: 2
    swap_dest: /var/spool/swap/swapfile
  tasks:
    - name: install commmon packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - epel-release
        - firewalld
        - yum-utils
        - sudo
    - name: Enable EPEL repo
      yum_repository:
        name: epel
        description: "Extra Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch"
        mirrorlist: "https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch"
        failovermethod: priority
        enabled: yes
        gpgcheck: yes
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    - name: install bash-completion
      yum:
        update_cache: yes
        name: bash-completion
        state: latest
    - name: install etckeeper
      yum:
        update_cache: yes
        name: etckeeper
        state: latest
    - name: install fail2ban
      yum:
        update_cache: yes
        name: fail2ban
        state: latest
    - name: Ensure fail2ban log setting
      ini_file:
        path: /etc/fail2ban/fail2ban.conf
        section: Definition
        option: logtarget
        value: /var/log/fail2ban.log
    - name: Ensure fail2ban jail settings
      ini_file:
        path: /etc/fail2ban/jail.d/local.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        create: yes
      with_items:
        - section: DEFAULT
          option: banaction
          value: firewallcmd-ipset
        - section: DEFAULT
          option: backend
          value: systemd
        - section: sshd
          option: enabled
          value: yes
    - name: for IDCF or Vultr
      block:
        - name: check swapfile exist
          stat:
            path: "{{ swap_dest }}"
          register: result
        - name: create swapfile
          block:
            - name: create swapfile directory
              file:
                path: "{{ swap_dest | dirname }}"
                state: directory
            - name: create swapfile
              file:
                path: "{{ swap_dest }}"
                owner: root
                group: root
                mode: 0600
                state: touch
            - name: initilize swapfile
              command: "dd if=/dev/zero of={{ swap_dest }} bs=1M count={{ swap_size * 1024 }}"
            - name: create swap
              command: "mkswap {{ swap_dest }}"
          when: not result.stat.exists
        - name: Ensure mounted swap
          mount:
            path: none
            src: "{{ swap_dest }}"
            fstype: swap
            opts: default
            state: present
      when:
        - packer_builder_type is defined
        - packer_builder_type in ['cloudstack', 'vultr']
    - name: Ensure active and enabled on system startup service
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - firewalld
        - fail2ban
