---
# code: language=ansible
- name: Setup Vagrant Image
  hosts: all
  become: true
  gather_facts: false
  vars:
    vbox_version: "{{ lookup('ansible.builtin.pipe', 'VBoxManage --version').split('r')[0] }}"
  pre_tasks:
    - name: Fetch Conneton ssh private key
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant"
        dest: "../files/vagrant"
        mode: "0600"
      become: false
      delegate_to: local
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - date_time
          - user
          - env
          - os_family
          - distribution
          - distribution_major_version
          - architecture
    - name: 01-base.sh
      block:
        - name: Modify sshd config
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^\\s*{{ item }}"
            line: "{{ item }} no"
          loop:
            - UseDNS
            - GSSAPIAuthentication
    - name: 01-base.sh
      block:
        - name: Modify sshd config
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^\\s*{{ item }}"
            line: "{{ item }} no"
          loop:
            - UseDNS
            - GSSAPIAuthentication
    - name: 02-vagrant.sh
      block:
        - name: Add authorized_key
          ansible.posix.authorized_key:
            user: "{{ ansible_facts.user_id }}"
            key: "{{ lookup('ansible.builtin.url', 'https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub') }}"
    - name: debian/pre-virtualbox.sh
      block:
        - name: Install dependency packages
          ansible.builtin.apt:
            name:
              - gcc
              - make
        - name: Purge xauth package
          ansible.builtin.apt:
            name: xauth
            purge: true
            autoremove: true
    - name: 03-virtualbox.sh
      block:
        - name: Debug
          ansible.builtin.debug:
            var: vbox_version
  post_tasks:
    - name: Cleaup packages
      ansible.builtin.apt:
        autoremove: true
        clean: true
