---
# code: language=ansible
- name: Setup Vagrant Image
  hosts: all
  become: true
  gather_facts: false
  vars:
    vbox_version: "{{ lookup('ansible.builtin.pipe', 'VBoxManage --version').split('r')[0] }}"
  # pre_tasks:
  #   - name: Fetch Conneton ssh private key
  #     ansible.builtin.get_url:
  #       url: "https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant"
  #       dest: "../files/vagrant"
  #       mode: "0600"
  #     become: false
  #     delegate_to: local
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - date_time
          - user
          - env
          - os_family
          - distribution
          - distribution_major_version
          - architecture
          - kernel
    - name: Find pratform variable file
      ansible.builtin.set_fact:
        variable_file: "{{ lookup('first_found', params, errors='ignore') }}"
      vars:
        params:
          files:
            - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}/{{ ansible_facts.distribution_major_version }}.yml"
            - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}.yml"
            - "{{ ansible_facts.os_family }}.yml"
          paths:
            - vars
    - name: Include variable file
      ansible.builtin.include_vars:
        file: "{{ variable_file }}"
      when: variable_file | length > 0
    - name: Find platform task file
      ansible.builtin.set_fact:
        include_task_file: "{{ lookup('first_found', params, errors='ignore') }}"
      vars:
        params:
          files:
            - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}/{{ ansible_facts.distribution_major_version }}.yml"
            - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}.yml"
            - "{{ ansible_facts.os_family }}.yml"
          paths:
            - tasks
    - name: Include task file
      ansible.builtin.include_tasks:
        file: "{{ include_task_file }}"
      when: include_task_file | length > 0
  post_tasks:
    - name: Find platform task file
      ansible.builtin.set_fact:
        include_task_file: "{{ lookup('first_found', params, errors='ignore') }}"
      vars:
        params:
          files:
            - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}/{{ ansible_facts.distribution_major_version }}.yml"
            - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}.yml"
            - "{{ ansible_facts.os_family }}.yml"
          paths:
            - post_tasks
    - name: Include task file
      ansible.builtin.include_tasks:
        file: "{{ include_task_file }}"
      when: include_task_file | length > 0
