<%
import datetime
%>\
Host overview
===================

% for hostname, host in sorted(hosts.items()):
${hostname}
-------------------

* **System**(`ansible_facts.system`): `${host['ansible_facts'].get('ansible_system', '')}`
* **OS Family**(`ansible_facts.os_family`): `${host['ansible_facts'].get('ansible_os_family', '')}`
* **Distribution**(`ansible_facts.distribution`): `${host['ansible_facts'].get('ansible_distribution', '')}`
* **Distribution major version**(`ansible_facts.distribution_major_version`): `${host['ansible_facts'].get('ansible_distribution_major_version', '')}`
* **Distribution release**(`ansible_facts.ansible_distribution_release`): `${host['ansible_facts'].get('ansible_distribution_release', '')}`
* **Package manager**(`ansible_facts.pkg_mgr`): `${host['ansible_facts'].get('ansible_pkg_mgr', '')}`
* **Architecture**(`ansible_facts.architecture`): `${host['ansible_facts'].get('ansible_architecture', '')}`
* **Kernel**(`ansible_facts.kernel`): `${host['ansible_facts'].get('ansible_kernel', '')}`

% endfor

---------------

Generated by [ansible-cmdb](https://github.com/fboender/ansible-cmdb) on ${datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}
