<%
import datetime
%>\
Host overview
===================

% for hostname, host in sorted(hosts.items()):
${hostname}
-------------------

* **System**: ${host['ansible_facts'].get('ansible_system', '')}
* **OS Family**: ${host['ansible_facts'].get('ansible_os_family', '')}
* **Distribution**: ${host['ansible_facts'].get('ansible_distribution', '')}
* **Distribution major version**: ${host['ansible_facts'].get('ansible_distribution_major_version', '')}
* **Distribution release**: ${host['ansible_facts'].get('ansible_distribution_release', '')}
* **Package manager**: ${host['ansible_facts'].get('ansible_pkg_mgr', '')}
* **Architecture**: ${host['ansible_facts'].get('ansible_architecture', '')}
* **Kernel**: ${host['ansible_facts'].get('ansible_kernel', '')}

% endfor

---------------

Generated by [ansible-cmdb](https://github.com/fboender/ansible-cmdb) on ${datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}
