- name: Display Server Info
  hosts: all
  gather_facts: true
  tasks:
    - name: Display Server Info
      ansible.builtin.debug:
        msg: |
          os_family: {{ ansible_facts['os_family'] }}
          distribution: {{ ansible_facts['distribution'] }}
          distribution_release: {{ ansible_facts['distribution_release'] }}
          distribution_major_version: {{ ansible_facts['distribution_major_version'] }}
          machine: {{ ansible_facts['machine'] }}
