---
roles:
  - name: common
    src: https://github.com/wate/ansible-role-common
    version: develop
  - name: nodejs
    src: https://github.com/wate/ansible-role-nodejs
    version: develop
  - name: nginx
    src: https://github.com/wate/ansible-role-nginx
    version: develop
  - name: php
    src: https://github.com/wate/ansible-role-php
    version: develop
  - name: mariadb
    src: https://github.com/wate/ansible-role-mariadb
    version: develop
  - name: php
    src: https://github.com/wate/ansible-role-php
    version: develop
  - name: tools
    src: https://github.com/wate/ansible-role-tools
    version: develop
collections: []
